name: Formatter

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          FILES=$(git ls-files '*.c' '*.cpp' '*.h' '*.hpp')
          if [ -n "$FILES" ]; then
            clang-format -i $FILES
          fi

      - name: Commit changes if any
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "Apply clang-format"
            git push
          fi
