name: GCC build linux

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  gcc-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (GCC)
        run: |
          sudo apt update
          sudo apt install -y build-essential
          g++ --version
      
      - name: build
        run: |
          echo "Building with GCC on Linux..."