name: Clang build linux

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  clang-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (Clang)
        run: |
          sudo apt update
          sudo apt install -y clang
          clang++ --version
      
      - name: build
        run: |
          echo "Building with Clang on Linux..."
          ./scripts/engine/setup_all_and_run_linux.sh