name: Clang build linux

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (Clang)
        run: |
          sudo apt update
          sudo apt install -y clang
          clang++ --version
