name: Clang build mac

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  clang-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (Clang)
        run: clang++ --version
      
      - name: build
        run: |
          echo "Building with Clang on macOS..."
          ./scripts/engine/setup_all_and_run_macos.sh