name: GCC build mac

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  gcc-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (GCC)
        run: |
          brew install gcc
          g++-14 --version
      
      - name: build