name: Shell Formatter

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  shfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v4.0.1
        with:
          shfmt-version: latest

      - name: Format all shell scripts
        run: |
          echo "Formatting all .sh files"
          shfmt -w .

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply shfmt formatting"
          branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
