name: MSVC build windows

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  msvc-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (MSVC)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Show compiler version
        run: cl
      
      - name: build
        run: |
        echo "Building with MSVC on Windows..."