name: GCC windows build

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  gcc-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (MinGW GCC)
        run: |
          choco install mingw -y
          g++ --version
      
      - name: build
        run: |
          echo "Building with GCC on Windows..."
          .\scripts\engine\setup_all_and_run_windows.bat