name: Clang build windows

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  clang-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install compiler (Clang-CL)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Show compiler version
        run: clang-cl --version
      
      - name: build
        run: |
          echo "Building with Clang on Windows..."
          .\scripts\engine\setup_all_and_run_windows.bat